# Database (env only)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Hibernate (SAFE)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Disable detailed errors
server.error.include-stacktrace=never
server.error.include-message=never
server.error.include-binding-errors=never
server.forward-headers-strategy=framework

# JWT (env only)
jwt.access.secret=${JWT_ACCESS_SECRET}
jwt.refresh.secret=${JWT_REFRESH_SECRET}
app.cookie.secure=true