# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/printova
spring.datasource.username=postgres
spring.datasource.password=postgres

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Debug logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# JWT (local fallback)
jwt.access.secret=mZ9xwTBRKPLqJHcYuEo2NfDVa7LsXr8pph6WQF3yXkCt5HV/91aGSYrjKBEHgLZTNV2zwM/s8PHo9rIQnkB4vw==
jwt.refresh.secret=pR4gwQDUOHNjGRPuLsKSoPLZg1Xmcxtppy7VRC2yXhYt6HV/O2hGSYqjKCEHgKYSNU3zwK/s6PHo8pIQnjB2vx==
app.cookie.secure=false